WebServer/Controllers/AdminController.cs
using CoreCA.DataModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebServer.ViewModels;

namespace WebServer.Controllers
{
    [Authorize(Policy = Constants.AdminPolicy)]
    public class AdminController : Controller
    {
        private readonly IMoviesCertContext _certContext;
        public AdminController(IMoviesCertContext certContext)
        {
            _certContext = certContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var stats = new AdminStats();
            stats.NumIssuedCertificates = _certContext.PublicCertificates.Count();
            stats.NumRevokedCertificates = _certContext.PublicCertificates.Count(c => c.IsRevoked);
            stats.CurrentSerialNum = _certContext.PublicCertificates
                .Select(c => c.SerialNr)
                .OrderByDescending(s => s)
                .FirstOrDefault();

            return View(stats);
        }
    }
}

WebServer/Controllers/CertController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebServer.ViewModels;
using WebServer.Models;
using WebServer.Models.Cert;
using CoreCA.Client;
using System.Security.Claims;
using System.Net.Mime;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Extensions.Caching.Memory;

namespace WebServer.Controllers
{
    [Authorize]
    public class CertController : Controller
    {
        private readonly CoreCAClient _client;
        private readonly ILogger<CertController> _logger;
        private readonly IMoviesCertContext _certContext;
        private readonly IMemoryCache _memoryCache;

        public CertController(CoreCAClient client, ILogger<CertController> logger, IMoviesCertContext certContext, IMemoryCache memoryCache)
        {
            _client = client;
            _logger = logger;
            _certContext = certContext;
            _memoryCache = memoryCache;
        }

        private CertificatesData FetchCertificatesData()
        {
            string uid = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var valid = _certContext.PublicCertificates
                .Where(c => c.Uid == uid)
                .AsEnumerable()
                .Where(c =>
                c.Parse().NotBefore <= DateTime.Now &&
                DateTime.Now <= c.Parse().NotAfter &&
                !c.IsRevoked)
                .Select(c => new Certificate(c));

            var revoked = _certContext.PublicCertificates
                .Where(c => c.Uid == uid)
                .AsEnumerable()
                .Where(c => c.IsRevoked)
                .Select(c => new Certificate(c));

            var expired = _certContext.PublicCertificates
                .Where(c => c.Uid == uid)
                .AsEnumerable()
                .Where(c =>
                DateTime.Now > c.Parse().NotAfter &&
                !c.IsRevoked)
                .Select(c => new Certificate(c));

            var data = new CertificatesData()
            {
                Valid = valid,
                Revoked = revoked,
                Expired = expired,
            };

            return data;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = FetchCertificatesData();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Download()
        {
            string uid = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string certb64 = null;
            // Try to see if a prior POST to Download or New cached a B64-encoded cert in TempData
            if (_memoryCache.TryGetValue($"{uid}.CertB64", out object certb64Obj))
                certb64 = certb64Obj as string;

            if (certb64 == null)
            {
                TempData["ErrorMessage"] = "Certificate download failed.";
                return RedirectToAction(nameof(Index));
            }

            byte[] certBytes = Convert.FromBase64String(certb64);
            return File(certBytes, MediaTypeNames.Application.Octet, "certificate_with_private_key.pfx");
        }

        [HttpPost]
        public async Task<IActionResult> Download(DownloadCertDetails details)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = FetchCertificatesData();
                viewModel.DownloadCertDetails = details;

                TempData["ErrorMessage"] = "Certificate download failed.";

                return View(nameof(Index), viewModel);
            }

            string uid = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string certb64 = await _client.DownloadPrivateKey(uid, details.Password);

            if (certb64 == null)
            {
                TempData["ErrorMessage"] = "Certificate download failed.";
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = "Certificate downloaded.";
            _memoryCache.Set($"{uid}.CertB64", certb64, DateTimeOffset.UtcNow.AddMinutes(1));

            TempData["AutoDownloadNewCert"] = Url.Action(nameof(Download), null, null, Request.Scheme);

            return RedirectToAction(nameof(Index));
        }

        // TODO: Rate limit
        [HttpPost]
        public async Task<IActionResult> New(RequestNewCertDetails details)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = FetchCertificatesData();
                viewModel.RequestNewCertDetails = details;

                TempData["ErrorMessage"] = "New certificate request failed.";

                return View(nameof(Index), viewModel);
            }

            string uid = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string certb64 = await _client.RequestNewCertificate(uid, details.Password, details.Passphrase);

            if (certb64 == null)
            {
                TempData["ErrorMessage"] = "New certificate request failed.";
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = "Certificate issued successfully.";
            TempData["AutoDownloadNewCert"] = Url.Action(nameof(Download), null, null, Request.Scheme);
            _memoryCache.Set($"{uid}.CertB64", certb64, DateTimeOffset.UtcNow.AddMinutes(1));

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Revoke()
        {
            string uid = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            bool success = await _client.RevokeCertificate(uid);

            if (success)
            {
                TempData["SuccessMessage"] = "Certificate revoked successfully.";
            }
            else
            {
                TempData["ErrorMessage"] = "Revoking certificate failed.";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

WebServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Applied Security Lab AS2019</title>
    <link rel="stylesheet" href="~/static/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="~/static/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Account" asp-action="Index">iMovies CA Web Interface</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cert" asp-action="Index">Certificates</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.HasClaim(c => c.Type == CoreCA.DataModel.Constants.AdminClaim))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Admin dashboard</a>
                            </li>
                        }
                        </ul>
                </div>
                <div class="navbar-collapse collapse order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.Identity.AuthenticationType == Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme)
                            {
                                <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="btn btn-link nav-link text-dark border-0">Log out</button>
                                </form>
                                </li>
                             }
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <script src="~/static/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/static/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; iMovies 2019
        </div>
    </footer>

    <script src="~/static/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>